#!/bin/bash

#$ -cwd
#$ -l h_rt=48:00:00,h_data=4G
#$ -M $USER@mail
#$ -m e
#$ -o /u/home/n/nzeltser/project-ngarud/TARA/fastq/batch5/output_log
#$ -j y
#$ -t 1-45:1


####Load Virtual Environment For Python 2.7 Based MIDAS####

. /u/local/Modules/default/init/modules.sh
module load python/anaconda2

. /u/local/apps/anaconda2/etc/profile.d/conda.sh

conda activate python2_env

#### Export MIDAS Environmental Variables ####

export PYTHONPATH=/u/local/compilers/intel/18.0.4/advisor_2018/pythonapi:/u/project/ngarud/nzeltser/MIDAS
export PATH=$PATH:/u/project/ngarud/nzeltser/MIDAS/scripts
export MIDAS_DB=/u/project/ngarud/Garud_lab/midas_db_v1.2

#### Setup For Job Array To Hoffman2 Cluster Goes Here ####

## Read in accession numbers as task array
readarray -t accs < /u/project/ngarud/nzeltser/TARA/fastq/batch5/fastq_accessions_5.txt 

## Set task ID variable to start at zero (instead of one) so that array may be indexed starting from 0
(( i=$SGE_TASK_ID - 1 ))

## Print information to help identify this job
echo "This is sub-job $SGE_TASK_ID"
echo "This is accession number ${accs[$i]}"


#### MIDAS Command Goes Here ####

## Format:
## /Path/to/MIDAS/Script species /path/to/output -1 /path/to/input/fastq

## Version of command for a job array:

## Species ##
#./MIDAS/scripts/run_midas.py species /u/scratch/n/nzeltser/midas/samples/${accs[$i]} -1 TARA/fastq/batch6/${accs[$i]}_1.fastq.gz -2 TARA/fastq/batch6/${accs[$i]}_2.fastq.gz

## Genes ##
./MIDAS/scripts/run_midas.py genes /u/scratch/n/nzeltser/midas/samples/${accs[$i]} -1 TARA/fastq/batch5/${accs[$i]}_1.fastq.gz -2 TARA/fastq/batch5/${accs[$i]}_2.fastq.gz

## Version of command for a single sample:
# ./MIDAS/scripts/run_midas.py species /u/scratch/n/nzeltser/simulated/unif_tenx_R1 -1 /u/scratch/n/nzeltser/simulated/unif_tenx_reads_R1.fastq

# ./MIDAS/scripts/run_midas.py species /u/scratch/n/nzeltser/midas/test_runs/re-downloaded_tara_${accs[$i]} -1 /u/scratch/n/nzeltser/midas/re-downloaded_TARA/${accs[$i]}_1.fastq
